### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Alexkerl** [kururuken/BERT-Transformer-for-Summarization#14]
修改了
将train.py 277行：pred, _ = model.beam_decode(batch[0], batch[1]) 改为 pred, _ = model.beam_decode(batch[0], batch[1], 3, 3)
报错
Traceback (most recent call last):
  File "train.py", line 277, in <module>
    pred, _ = model.beam_decode(batch[0], batch[1], 3, 3)
  File "/root/_project/summarization-bert-transformer/model.py", line 200, in beam_decode
    active_inst_idx_list = beam_decode_step(
  File "/root/_project/summarization-bert-transformer/model.py", line 162, in beam_decode_step
    dec_seq = prepare_beam_dec_seq(inst_dec_beams, len_dec_seq)
  File "/root/_project/summarization-bert-transformer/model.py", line 138, in prepare_beam_dec_seq
    dec_partial_seq = [b.get_current_state() for b in inst_dec_beams if not b.done]
  File "/root/_project/summarization-bert-transformer/model.py", line 138, in <listcomp>
    dec_partial_seq = [b.get_current_state() for b in inst_dec_beams if not b.done]
  File "/root/_project/summarization-bert-transformer/transformer/Beam.py", line 33, in get_current_state
    return self.get_tentative_hypothesis()
  File "/root/_project/summarization-bert-transformer/transformer/Beam.py", line 90, in get_tentative_hypothesis
    hyps = [self.get_hypothesis(k) for k in keys]
  File "/root/_project/summarization-bert-transformer/transformer/Beam.py", line 90, in <listcomp>
    hyps = [self.get_hypothesis(k) for k in keys]
  File "/root/_project/summarization-bert-transformer/transformer/Beam.py", line 100, in get_hypothesis
    hyp.append(self.next_ys[j+1][k])
IndexError: tensors used as indices must be long, byte or bool tensors

版本为torch1.6

**Comment by v587su** [comment]
torch版本问题，退到1.4即可

**Comment by leesin5079** [comment]
> torch版本问题，退到1.4即可

没用啊老哥，不是版本问题。

**Comment by chenzelong** [comment]
我也遇到了，你解决了吗？

**Comment by 2237995998** [comment]
修改Beam.py中的
hyp.append(self.next_ys[j+1][k].type(torch.long))
 k = self.prev_ks[j][k].type(torch.long)
就可以解决了。跟torch版本没关系，但是这个模型的效果极其差
